from . import views
from django.urls import path

urlpatterns = [
    path('',views.AboutView.as_view(), name = 'about'),
    path('search/', views.search, name='search'),
    path('documents/', views.DocumentView.as_view(), name='documents'),
    path('documents/<int:document_id>/',views.DocumentViewList.as_view(), name='document-view'),
    path('documents/main-documents/', views.documents_main_list, name='main_documents'),
    path('documents/regular-docs/', views.regular_document_list, name='docs_reg'),
    path('news/', views.PostList.as_view(), name='news'),
    path('about/tasks/', views.TasksView.as_view(), name='tasks'),
    path('about/managment/', views.MangmentView.as_view(), name='managment'),
    path('about/information/', views.InformationView.as_view(), name='information'),
    path('about/ifs/', views.IfsView.as_view(), name='ifs'),
    path('about/structure', views.StructureView.as_view(), name='structure'),
    path('about/synopsis/', views.SynopsisView.as_view(), name='synopsis'),
    path('about/procuroment', views.ProcuromentView.as_view(), name='procuroment'),
    path('about/staffing/', views.StuffingView.as_view(), name='stuffing'),
    path('about/plans/<int:plans_id>', views.PlansViewList.as_view(), name='plan-view'),
    path('about/plans/', views.plans_material, name='about-plans'),
    path('about/examinations/<int:exam_id>', views.ExaminationsViewList.as_view(), name='exams-view'),
    path('about/examinations/', views.exams_material, name='about-exams'),
    path('anti_corruption/<int:anti_corruption_id>/', views.AntiCorruptionViewList.as_view(), name='anti_corruption-view'),
    path('anti-corruption/', views.AntiCorruption.as_view(), name='anti-corruption'),
    path('anti-corruption/expertise/', views.anti_corruption_expertise, name='expertise'),
    path('anti-corruption/materials/', views.anti_corruption_materials, name='materials'),
    path('activities/', views.ActivitiesView.as_view(), name='activities'),
    path('activities/<int:activities_id>/',views.ActivitiesViewList.as_view(), name='activities-view'),
    path('activities/reports', views.activities_report_main_list , name='reports'),
    path('activities/control-activities/', views.activities_control_main_list, name='control'),
    path('activities/analytical/', views.activities_analitycal_main_list, name='analytical'),
    path('activities/college/', views.activities_college_main_list, name='college'),
    path('activities/info/', views.activities_info_main_list, name='info'),
    path('activities/statements/', views.activities_statements_main_list, name='statements'),
    path('activities/events/', views.activities_events_main_list, name='events'),
    path('activities/solutions/', views.activities_solutions_main_list, name='solutions'),
    path('activities/plans/', views.activities_plans_main_list, name='plans'),
    path('activities/publications/', views.activities_publications_main_list, name='publications'),
    path('activities/plan-of-audits/', views.activities_audit_main_list, name='audit'),
    path('news/<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('feedback', views.FeedbackCreateView.as_view(), name='feedback_form'),
    path('feedback/load-more/', views.FeedbackListView.as_view(), name='feedback_ajax'),
    path('all-news', views.function_based, name='all_posts'),
    path('communication', views.Connection.as_view(), name='communication'),
]