# Generated by Django 4.1.7 on 2023-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_cover_alter_post_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='IMAGE.png', upload_to='images'),
        ),
    ]
