# Generated by Django 4.1.7 on 2023-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
