# Generated by Django 4.1.7 on 2023-03-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
