# Generated by Django 4.1.7 on 2023-04-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
