# Generated by Django 4.1.7 on 2023-05-31 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_documents_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='link',
        ),
        migrations.AddField(
            model_name='documents',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='Документ'),
        ),
    ]
