# Generated by Django 4.1.7 on 2023-06-06 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_documents_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Название')),
                ('document', models.FileField(blank=True, max_length=255, null=True, upload_to='activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('status', models.IntegerField(choices=[(0, 'Годовой отчет'), (1, 'Контрольные мероприятия'), (2, 'Экспертно-аналитические мероприятия'), (3, 'Коллегия'), (4, 'Официальные выступления и заявления'), (5, 'Сведения о внесенных мероприятиях'), (6, 'Сведения о принятых решениях'), (7, 'План работы КСП'), (8, 'Публикации в СМИ'), (9, 'План внутреннего финансового аудита')], default=0, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Деятельность',
                'verbose_name_plural': 'Деятельность',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Название'),
        ),
    ]
