# Generated by Django 4.1.7 on 2023-06-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_activities_alter_documents_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.IntegerField(choices=[(0, 'Годовой отчет'), (1, 'Контрольные мероприятия'), (2, 'Экспертно-аналитические мероприятия'), (3, 'Коллегия'), (4, 'Информация о заключенных соглашениях'), (5, 'Официальные выступления и заявления'), (6, 'Сведения о внесенных мероприятиях'), (7, 'Сведения о принятых решениях'), (8, 'План работы КСП'), (9, 'Публикации в СМИ'), (10, 'План внутреннего финансового аудита')], default=0, verbose_name='Тип документа'),
        ),
    ]
