# Generated by Django 4.1.7 on 2023-06-10 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_activities_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anti_corrupsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('document', models.FileField(blank=True, max_length=255, null=True, upload_to='anti-corruption/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Деятельность',
                'verbose_name_plural': 'Деятельность',
                'ordering': ['-created_at'],
            },
        ),
    ]
