# Generated by Django 4.1.7 on 2023-06-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_anti_corrupsion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anti_corrupsion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Противодействие коррупции', 'verbose_name_plural': 'Противодействие коррупции'},
        ),
    ]
