# Generated by Django 4.1.7 on 2023-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_anti_corrupsion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anti_corrupsion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Сведения о доходах и имуществе'), (1, 'Методические материалы')], default=0, verbose_name='Тип документа'),
        ),
    ]
