# Generated by Django 4.1.7 on 2023-06-19 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_anti_corrupsion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='anti_corrupsion',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='anti-corruption/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ'),
        ),
    ]
