# Generated by Django 4.1.7 on 2023-07-19 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_feedback_answer_alter_anti_corrupsion_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('document', models.FileField(blank=True, max_length=500, null=True, upload_to='anti-corruption/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('status', models.IntegerField(choices=[(0, 'Сведения о доходах и имуществе'), (1, 'Методические материалы')], default=0, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Противодействие коррупции',
                'verbose_name_plural': 'Противодействие коррупции',
                'ordering': ['-created_at'],
            },
        ),
    ]
