# Generated by Django 4.1.7 on 2023-07-19 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'ordering': ['-created_at'], 'verbose_name': 'План', 'verbose_name_plural': 'План'},
        ),
        migrations.RemoveField(
            model_name='plans',
            name='status',
        ),
        migrations.AlterField(
            model_name='plans',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='plans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ'),
        ),
    ]
