# Generated by Django 4.1.7 on 2023-10-09 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_plans_options_remove_plans_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('document', models.FileField(blank=True, max_length=500, null=True, upload_to='control_activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Контрольные мероприятия',
                'verbose_name_plural': 'Контрольные мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('document', models.FileField(blank=True, max_length=500, null=True, upload_to='examinations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Экспертизы',
                'verbose_name_plural': 'Экспертизы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expert_analyticalActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('document', models.FileField(blank=True, max_length=500, null=True, upload_to='expert-analytical-activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Документ')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Экспертно-аналитические мероприятия',
                'verbose_name_plural': 'Экспертно-аналитические мероприятия',
                'ordering': ['-created_at'],
            },
        ),
    ]
